openapi: 3.0.0
info:
  version: 1.0.0
  title: RaspiClus API
  description: Documentation of a RaspiClus openapi

tags:
  - name: Clusters
  - name: RaspberryPis
  - name: Systems
  - name: Administration

paths:
  /clusters:
    get:
      description: "Return list of all cluster objects"
      summary: "GetAllclusters"
      operationId: src.adapters.rest_api.clusters.get_clusters
      tags:
        - Clusters
      responses:
        200:
          $ref: "#/components/responses/ClustersResponse200"
    post:
      description: "Used to add new file"
      summary: "AddCluster"
      operationId: src.adapters.rest_api.clusters.add_cluster
      tags:
        - Clusters
      requestBody:
        $ref: "#/components/requestBodies/ClusterAddBody"
      responses:
        201:
          $ref: "#/components/responses/ClusterObjectCreated201"
        400:
          $ref: "#/components/responses/CorruptedRequest400"
    
  /clusters/{id}:
    get:
      description: "Get specific Cluster"
      summary: "GetCluster"
      operationId: src.adapters.rest_api.clusters.get_cluster
      tags:
        - Clusters
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: "Identification number in UUID4 format."
      responses:
        200:
          $ref: "#/components/responses/ClusterResponse200"
        404:
          $ref: "#/components/responses/EntityNotFound404"

  /raspberries:
    get:
      description: "Returns list of all Raspberries objects"
      summary: "GetAllRaspberries"
      operationId: src.adapters.rest_api.raspberry_pis.get_raspberries
      tags:
        - RaspberryPis
      responses:
        200:
          $ref: "#/components/responses/RaspberriesResponse200"
    post:
      description: "Allows to add a Raspberry Pi"
      summary: "AddRaspberryPi"
      operationId: src.adapters.rest_api.raspberry_pis.add_raspberry_pi
      tags:
        - RaspberryPis
      requestBody:
        $ref: "#/components/requestBodies/RaspberryPiAddBody"
      responses:
        201:
          $ref: "#/components/responses/RaspberryPiObjectCreated201"
        400:
          $ref: "#/components/responses/CorruptedRequest400"

  /raspberries/{mac_address}:
    get:
      description: "Return single Raspberry Pi"
      summary: "GetRaspberryPi"
      operationId: src.adapters.rest_api.raspberry_pis.get_single_raspberry
      tags:
        - RaspberryPis
      parameters:
        - in: path
          name: mac_address
          schema:
            type: string
          required: true
          description: "Mac Address of RaspberryPi ethernet adapter"
      responses:
        200:
          $ref: "#/components/responses/RaspberryPiResponse200"
        404:
          $ref: "#/components/responses/EntityNotFound404"

    post:
      description: "Allows to change Operating System on given Raspberry system"
      summary: "ChangeRaspberryOS"
      operationId: src.adapters.rest_api.raspberry_pis.change_os
      tags:
        - RaspberryPis
      parameters:
        - in: path
          name: mac_address
          schema:
            type: string
          required: true
          description: "Identification number of RaspberryID"
      requestBody:
        $ref: "#/components/requestBodies/ChangeOSBody"
      responses:
        204:
          $ref: "#/components/responses/SystemChangedResponse204"
        404:
          $ref: "#/components/responses/EntityNotFound404"

  /raspberries/{mac_address}/refresh:
    post:
      description: "When called, orders given machine to refresh it's OS to a new fresh copy"
      summary: "RefreshOSImage"
      operationId: src.adapters.rest_api.raspberry_pis.refresh_os
      tags:
        - RaspberryPis
      parameters:
        - in: path
          name: mac_address
          schema:
            type: string
          required: true
          description: "Mac address of the adapter used to connect to the server"
      responses:
        204:
          $ref: "#/components/responses/SystemChangedResponse204"
        404:
          $ref: "#/components/responses/EntityNotFound404"


  /operating_systems:
    get:
      description: "Returns list of all Operating Systems objects"
      summary: "GetAllOSes"
      operationId: src.adapters.rest_api.operating_systems.get_operating_systems
      tags:
        - Systems
      responses:
        200:
          $ref: "#/components/responses/OperatingSystemsResponse200"
#    post:
#      description: "Allows to add Operating System"
#      summary: "AddOperatingSystem"
#      operationId: src.adapters.rest_api.operating_systems.add_operating_system
#      tags:
#        - Systems
#      requestBody:
#        $ref: "#/components/requestBodies/OSAddBody"
#      responses:
#        201:
#          $ref: "#/components/responses/OperatingSystemObjectCreated201"
#        400:
#          $ref: "#/components/responses/CorruptedRequest400"

  /operating_systems/{id}:
    get:
      description: "Return single Operating System information"
      summary: "GetOperatingSystem"
      operationId: src.adapters.rest_api.operating_systems.get_single_os
      tags:
        - Systems
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: "Identification number in UUID4 format."
      responses:
        200:
          $ref: "#/components/responses/OperatingSystemResponse200"
        404:
          $ref: "#/components/responses/EntityNotFound404"

  /health/{raspberry_id}:
    post:
      description: "Updates Raspberry Pi with information if it's alive"
      summary: "UpdateRaspberryPiAliveStatus"
      operationId: src.adapters.rest_api.health.health_status
      tags:
        - Administration
      parameters:
        - in: path
          name: raspberry_id
          schema:
            type: string
          required: true
          description: "Identification number of RaspberryPi"
      responses:
        204:
          $ref: "#/components/responses/OperatingSystemResponse200"
        404:
          $ref: "#/components/responses/EntityNotFound404"

components:
  responses:
    CorruptedRequest400:
      description: "Incorrect request"
      content:
        application/json:
          schema:
            type: string
            example: "Request body was incorrect"
    
    EntityNotFound404:
      description: "Not found entity"
      content:
        application/json:
          schema:
            type: string
            example: "Object couldn't be located."

    ClustersResponse200:
      description: "Response object of 200"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ClusterList"
    
    ClusterResponse200:
      description: "Object of Cluster"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ClusterObject"

    ClusterObjectCreated201:
      description: "Cluster has been added."
      content:
        application/yaml:
          schema:
            $ref: "#/components/schemas/ClusterObject"

    RaspberriesResponse200:
      description: "Response for Raspberries list"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RaspberryPisList"

    RaspberryPiResponse200:
      description: "Response with Raspberry Pi"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RaspberryPiObject"

    RaspberryPiObjectCreated201:
      description: "Response to successful RaspberryPi creation"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RaspberryPiObject"

    SystemChangedResponse204:
      description: "Response to successful OS changed"

    OperatingSystemsResponse200:
      description: "Response to getting the list of RaspberryPis"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OperatingSystemsList"

    OperatingSystemObjectCreated201:
      description: "Informs that adding new OS has been successful"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OperatingSystemObject"

    OperatingSystemResponse200:
      description: "Response to request for a single Operating System"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OperatingSystemObject"

  requestBodies:
    ClusterAddBody:
      description: "Body of Cluster to add."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Cluster"

    RaspberryPiAddBody:
      description: "Body of a Raspberry Pi"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RaspberryPi"

    ChangeOSBody:
      description: "Body of changing OS for Raspberry"
      content:
        application/json:
          schema:
            properties:
              os_id:
                type: string
                example: "11212-adasr12-1241rfa-12412"

    OSAddBody:
      description: "Description for a body of Oparating System"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OperatingSystem"

  schemas:
    Cluster:
      description: Representation of Cluster
      type: object
      properties:
        name:
          type: string
          example: "Johney"
        network:
          type: string
          example: "192.168.50.11/32"

    ClusterObject:
      description: Representation of Cluster stored in the system
      allOf:
        - $ref: "#/components/schemas/Cluster"
        - type: object
          properties:
            id:
              type: string
              example: "1c43edb8-75ec-47bc-92eb-b3f6b1c399ef"
            raspberry_pis:
              type: array
              items:
                type: string
                example:
                  - "1c43edb8-75ec-47bc-92eb-b3f6b1c399ef"
                  - "1c43edb8-753c-47bc-92eb-b3f6b1c399ef"


    ClusterList:
      description: List of Cluster objects
      type: array
      items:
        $ref: "#/components/schemas/ClusterObject"

    RaspberryPi:
      description: Represents object of RaspberryPi
      type: object
      properties:
        name:
          type: string
          example: "Raspberry_1"
        address:
          type: string
          example: "192.168.50.11"
        operating_system_id:
          type: string
          example: "148-0fasjfa=r-15-ija;f"
        mac_address:
          type: string
          example: "8A4f1b23c454"
        serial_number:
          type: string
          example: "328b9d26"

    RaspberryPiObject:
      description: Represents RaspberryPi object stored in system
      allOf:
        - $ref: "#/components/schemas/RaspberryPi"
        - type: object
          properties:
            id:
              type: string
              example: "148-0fasjfa=r-15-ija;f"

    RaspberryPisList:
      description: Represents list of RaspberryPi objects
      type: array
      items:
        $ref: "#/components/schemas/RaspberryPiObject"

    OperatingSystem:
      description: Representation of Operating System
      type: object
      properties:
        name:
          type: string
          example: "Ubuntu 22.04"
        path:
          type: string
          example: "/mnt/os_images/ubuntu_22_04"
        os_type:
          type: string
          example: "Golden"

    OperatingSystemObject:
      description: Represents Operating System object stored in the system
      allOf:
        - $ref: "#/components/schemas/OperatingSystem"
        - type: object
          properties:
            id:
              type: string

    OperatingSystemsList:
      description: Represents list of Operating Systems objects
      type: array
      items:
        $ref: "#/components/schemas/OperatingSystem"