version: "3.6"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - raspi_clus:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  raspi_clus: